apiVersion: v1
kind: Service
metadata:
  name: sink-display
  namespace: vanus
spec:
  selector:
    app: sink-display
  type: ClusterIP
  ports:
    - port: 8080
      name: sink-display
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink-display
  namespace: vanus
  labels:
    app: sink-display
spec:
  selector:
    matchLabels:
      app: sink-display
  replicas: 1
  template:
    metadata:
      labels:
        app: sink-display
    spec:
      containers:
      - name: sink-display
        image: public.ecr.aws/vanus/connector/sink-display:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"