apiVersion: v1
kind: ConfigMap
metadata:
  name: source-tencentcloud-cos
  namespace: vanus
data:
  config.yml: |-
    v_target: "35.87.170.130:8080"
    eventbus: "demo"
    bucket:
      endpoint: "vanus-1253760853.cos.ap-beijing.myqcloud.com"
    function:
      region: "ap-beijing"

---
apiVersion: v1
kind: Secret
metadata:
  name: source-tencentcloud-cos
  namespace: vanus
type: Opaque
data:
  # cat secret.yml | base64
  secret.yml: |
    c2VjcmV0X2lkOiAiQUtJRFdxNDh5Y3J3blc2U2RjWEZtMzNvR1VnY1E0VnMxdmRIIgpzZWNyZXRf
    a2V5OiAiVkNrQVp2ODdzNEVEcEVQVEwwU2ZlTjNYNjV1V3U1MWsiCg==
#  secret.yml:
#    secret_id: "AKIDWq48ycrwnW6SdcXFm33oGUgcQ4Vs1vdH"
#    secret_key: "VCkAZv87s4EDpEPTL0SfeN3X65uWu51k"
immutable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-tencentcloud-cos
  namespace: vanus
  labels:
    app: source-tencentcloud-cos
spec:
  selector:
    matchLabels:
      app: source-tencentcloud-cos
  replicas: 1
  template:
    metadata:
      labels:
        app: source-tencentcloud-cos
    spec:
      containers:
        - name: source-tencentcloud-cos
          image: public.ecr.aws/vanus/connector/source-tencentcloud-cos:dev
          imagePullPolicy: Always
          command: ["bash", "-c", "sleep 10000"]
          volumeMounts:
            - name: config
              mountPath: /vance/config
            - name: secret
              mountPath: /vance/secret
      volumes:
        - name: secret
          secret:
            secretName: source-tencentcloud-cos
        - name: config
          configMap:
            name: source-tencentcloud-cos