apiVersion: v1
kind: Service
metadata:
  name: sink-mysql
  namespace: vanus
spec:
  selector:
    app: sink-mysql
  type: ClusterIP
  ports:
    - port: 8080
      name: sink-mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sink-mysql
  namespace: vanus
data:
  config.yml: |-
    port: 8080
    db:
      host: "localhost"
      port: 3306
      username: "vanus_test"
      password: "123456"
      database: "vanus_test"
      table_name: "user"

    insert_mode: UPSERT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink-mysql
  namespace: vanus
  labels:
    app: sink-mysql
spec:
  selector:
    matchLabels:
      app: sink-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: sink-mysql
    spec:
      containers:
        - name: sink-mysql
          image: public.ecr.aws/vanus/connector/sink-mysql:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /vanus-connect/config
      volumes:
        - name: config
          configMap:
            name: sink-mysql