apiVersion: v1
kind: ConfigMap
metadata:
  name: source-postgres
  namespace: vanus
data:
  config.yaml: |-
    target: "http://localhost:8080"
    name: "quick_start"
    db:
      host: "localhost"
      port: 5432
      username: "vance_test"
      password: "123456"
      database: "vance_test"
    schema_include: [ "public" ]
    table_include: [ "public.user" ]

    slot_name: vance_slot
    publication_name: vance_publication
    
    store:
        type: FILE
        pathname: "/vance/data/offset.dat"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-postgres
  namespace: vanus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-postgres
  namespace: vanus
  labels:
    app: source-postgres
spec:
  selector:
    matchLabels:
      app: source-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: source-postgres
    spec:
      containers:
        - name: source-postgres
          image: public.ecr.aws/vanus/connector/source-postgres
          imagePullPolicy: Always
          volumeMounts:
            - name: source-postgres-config
              mountPath: /vance/config
            - name: source-postgres-data
              mountPath: /vance/data
      volumes:
        - name: source-postgres-config
          configMap:
            name: source-postgres
        - name: source-postgres-data
          persistentVolumeClaim:
            claimName: source-postgres