# receive event port
"port": 8080
# es address
"address": "http://localhost:9200"
# es index name
"index_name": "vance_test"
# es primary id from event key
"primary_key": "data.id"
"insert_mode": "upsert"
