apiVersion: v1
kind: ConfigMap
metadata:
  name: source-http
  namespace: vanus
data:
  config.yml: |-
    v_target: "xxxx"
    eventbus: "xxxxx"
    bucket:
      endpoint: "xxxxx.cos.ap-beijing.myqcloud.com"
    function:
      region: "ap-beijing"

---
apiVersion: v1
kind: Secret
metadata:
  name: source-http
  namespace: vanus
type: Opaque
data:
  # cat secret.yml | base64
  secret.yml: |
    xxxxx
immutable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-http
  namespace: vanus
  labels:
    app: source-http
spec:
  selector:
    matchLabels:
      app: source-http
  replicas: 1
  template:
    metadata:
      labels:
        app: source-http
    spec:
      containers:
        - name: source-http
          image: public.ecr.aws/vanus/connector/source-http:dev
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /vance/config
            - name: secret
              mountPath: /vance/secret
      volumes:
        - name: secret
          secret:
            secretName: source-http
        - name: config
          configMap:
            name: source-http