apiVersion: v1
kind: ConfigMap
metadata:
  name: source-mysql
  namespace: vanus
data:
  config.yml: |-
    target: "http://vanus-gateway.vanus:8080/gateway/quick_start"
    name: "quick_start"
    db:
      host: "localhost"
      port: 3306
      username: "root"
      password: "vanus123456"
    database_include: [ "dbname" ]
    # format is dbname.tableName
    table_include: [ "dbname.user" ]

    store:
      type: FILE
      pathname: "/vanus-connect/data/offset.dat"

    db_history_file: "/vanus-connect/data/history.dat"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-mysql
  namespace: vanus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-mysql
  namespace: vanus
  labels:
    app: source-mysql
spec:
  selector:
    matchLabels:
      app: source-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: source-mysql
    spec:
      containers:
        - name: source-mysql
          image: public.ecr.aws/vanus/connector/source-mysql
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /vanus-connect/config
            - name: data
              mountPath: /vanus-connect/data
      volumes:
        - name: config
          configMap:
            name: source-mysql
        - name: data
          persistentVolumeClaim:
            claimName: source-mysql