apiVersion: v1
kind: ConfigMap
metadata:
  name: source-aws-billing
  namespace: vanus
data:
  config.yml: |-
    "target": "http://vanus-gateway.vanus:8080/gateway/quick_start"
    secret:
      access_key_id: AKIAIOSFODNN7EXAMPLE
      secret_access_Key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-aws-billing
  namespace: vanus
  labels:
    app: source-aws-billing
spec:
  selector:
    matchLabels:
      app: source-aws-billing
  replicas: 1
  template:
    metadata:
      labels:
        app: source-aws-billing
    spec:
      containers:
        - name: source-aws-billing
          image: public.ecr.aws/vanus/connector/source-aws-billing
          imagePullPolicy: Always
          volumeMounts:
            - name: source-aws-billing-config
              mountPath: /vanus-connect/config
      volumes:
        - name: source-aws-billing-config
          configMap:
            name: source-aws-billing