apiVersion: v1
kind: ConfigMap
metadata:
  name: source-alicloud-billing
  namespace: vanus
data:
  config.yml: |-
    target: "http://vanus-gateway.vanus:8080/gateway/quick_start"
    secret:
      access_key_id: LTAI5t7eneojm6aeRKncB7V9
      secret_access_key: 26Fno8k0F7jtL2hUIrm4JTRF16jPLL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-alicloud-billing
  namespace: vanus
  labels:
    app: source-alicloud-billing
spec:
  selector:
    matchLabels:
      app: source-alicloud-billing
  replicas: 1
  template:
    metadata:
      labels:
        app: source-alicloud-billing
    spec:
      containers:
        - name: source-alicloud-billing
          image: public.ecr.aws/vanus/connector/source-alicloud-billing
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /vanus-connect/config
      volumes:
        - name: config
          configMap:
            name: source-alicloud-billing