apiVersion: v1
kind: Service
metadata:
  name: sink-tencentcloud-scf
  namespace: vanus
spec:
  selector:
    app: sink-tencentcloud-scf
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32555
      name: sink-tencentcloud-scf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sink-tencentcloud-scf
  namespace: vanus
data:
  config.yml: |-
    port: 8080
    secret:
      secret_id: ABID570jkkngFWl7uY3QchbdUXVIuNisywoA
      secret_key: xxxxxx
    function:
      name: "xxxxxx"
      region: "ap-beijing"
      namespace: "default"
    debug: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink-tencentcloud-scf
  namespace: vanus
  labels:
    app: sink-tencentcloud-scf
spec:
  selector:
    matchLabels:
      app: sink-tencentcloud-scf
  replicas: 1
  template:
    metadata:
      labels:
        app: sink-tencentcloud-scf
    spec:
      containers:
        - name: sink-tencentcloud-scf
          image: public.ecr.aws/vanus/connector/sink-tencentcloud-scf:dev
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /vanus-connect/config
      volumes:
        - name: config
          configMap:
            name: sink-tencentcloud-scf