apiVersion: v1
kind: Service
metadata:
  name: sink-tencentcloud-function
  namespace: vanus
spec:
  selector:
    app: sink-tencentcloud-function
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32555
      name: sink-tencentcloud-function
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sink-tencentcloud-function
  namespace: vanus
data:
  config.yml: |-
    port: 8080
    function:
      name: "xxxxxx"
      region: "ap-beijing"
      namespace: "default"
    debug: false

---
apiVersion: v1
kind: Secret
metadata:
  name: sink-tencentcloud-function
  namespace: vanus
type: Opaque
data:
  # cat secret.yml | base64
  secret.yml: |
    xxxxx
immutable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink-tencentcloud-function
  namespace: vanus
  labels:
    app: sink-tencentcloud-function
spec:
  selector:
    matchLabels:
      app: sink-tencentcloud-function
  replicas: 1
  template:
    metadata:
      labels:
        app: sink-tencentcloud-function
    spec:
      containers:
        - name: sink-tencentcloud-function
          image: public.ecr.aws/vanus/connector/sink-tencentcloud-function:dev
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /vance/config
            - name: secret
              mountPath: /vance/secret
      volumes:
        - name: secret
          secret:
            secretName: sink-tencentcloud-function
        - name: config
          configMap:
            name: sink-tencentcloud-function