apiVersion: v1
kind: Service
metadata:
  name: connector-mongo-sink
  namespace: vanus
spec:
  selector:
    app: connector-mongo-sink
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32001
      name: connector-mongo-sink
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connector-mongo-sink
  namespace: vanus
data:
  config.yml: |-
    db_hosts:
      - 44.242.140.28:27017
    port: 8080

---
apiVersion: v1
kind: Secret
metadata:
  name: connector-mongo-sink
  namespace: vanus
type: Opaque
data:
  # cat secret.yml | base64
  secert.yml: dXNlcm5hbWU6ICJ0ZXN0IgpwYXNzd29yZDogIjEyMzQ1NiIKYXV0aFNvdXJjZTogImFkbWluIg==
immutable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector-mongo-sink
  namespace: vanus
  labels:
    app: connector-mongo-sink
spec:
  selector:
    matchLabels:
      app: connector-mongo-sink
  replicas: 1
  template:
    metadata:
      labels:
        app: connector-mongo-sink
    spec:
      containers:
        - name: connector-mongo-sink
          image: public.ecr.aws/vanus/connector/mongodb-sink:v0.2.0-alpha
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /vance/config
            - name: secret
              mountPath: /vance/secret
          # env: see README for more about how to set env
      volumes:
        - name: secret
          secret:
            secretName: connector-mongo-sink
        - name: config
          configMap:
            name: connector-mongo-sink