apiVersion: v1
kind: Service
metadata:
  name: sink-doris
  namespace: vanus
spec:
  selector:
    app: sink-doris
  type: ClusterIP
  ports:
    - port: 8080
      name: sink-doris
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sink-doris
  namespace: vanus
data:
  config.yml: |-
    port: 8080
    secret:
      # doris info
      fenodes: "localhost:8030"
      db_name: "vanus_test"
      table_name: "user"
      username: "vanus_test"
      password: "123456"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink-doris
  namespace: vanus
  labels:
    app: sink-doris
spec:
  selector:
    matchLabels:
      app: sink-doris
  replicas: 1
  template:
    metadata:
      labels:
        app: sink-doris
    spec:
      containers:
        - name: sink-doris
          image: public.ecr.aws/vanus/connector/sink-doris
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /vanus-connect/config
      volumes:
        - name: config
          configMap:
            name: sink-doris
